### ISSUE TITLE
Wrong WARNING in meta_sai_on_fdb_event_single

### ISSUE THREAD

**Issue by pavel-shirshov** [Azure/sonic-sairedis#182]
When I removing FDB object which I created manually (not ASIC created it) I receive:
meta_sai_on_fdb_event_single: object key fdb:mac:02:09:87:65:43:21;vlan:2 don't exist but received AGED/FLUSHED event

**Comment by kcudnik** [comment]
can you provide steps so we could reproduce ?

**Comment by kcudnik** [comment]
so probably what happens you created it, removed and then asic sends event anyway
so your success removal is correct, and event from asic it is also corrent, this is not harmful i believe

ps. why this would be wrong warning ? it is warning since fdb don't exists since user removed it, there are some potential issues and rece conditions since event is asynchronous, for example you create fdb remve it and create it , so you expect there will be 1 fdb in db, but there will be 0, since first fdb event will came and it will remove your second fdb entry

there is no simple fix for that unles we will be able to distinguish fdb created by user and created by asic, but currently they are treated the same and there is no difference in DB for them.

lets discuss this offline

**Comment by stcheng** [comment]
let's check this issue on the latest image.
