### ISSUE TITLE
ASIC_STATE:SAI_OBJECT_TYPE_PORT has NULL:NULL field/value

### ISSUE THREAD

**Issue by stcheng** [Azure/sonic-sairedis#185]
```
127.0.0.1:6379[1]> hgetall ASIC_STATE:SAI_OBJECT_TYPE_PORT:oid:0x100000000001a
 1) "NULL"
 2) "NULL"
 3) "SAI_PORT_ATTR_FDB_LEARNING"
 4) "SAI_PORT_FDB_LEARNING_MODE_HW"
 5) "SAI_PORT_ATTR_ADMIN_STATE"
 6) "true"
 7) "SAI_PORT_ATTR_QOS_DSCP_TO_TC_MAP"
 8) "oid:0x130000000005e5"
 9) "SAI_PORT_ATTR_QOS_TC_TO_QUEUE_MAP"
10) "oid:0x130000000005eb"
11) "SAI_PORT_ATTR_QOS_TC_TO_PRIORITY_GROUP_MAP"
12) "oid:0x130000000005ea"
13) "SAI_PORT_ATTR_QOS_PFC_PRIORITY_TO_QUEUE_MAP"
14) "oid:0x130000000005e6"
15) "SAI_PORT_ATTR_PRIORITY_FLOW_CONTROL"
16) "24"
```

**Comment by kcudnik** [comment]
Yes, thats correct, since by default when syncd receive query from sairedis like get port list, then its doing snoop on that oid and puts it to db, but it have no idea on attributes on that port, so null:null is used to force it to be present in the db since there in redis hashes without entries are not shown. this is expected behaviour, and null:null is skipped in both syncd and sairedis, user don;t need to worry about this

**Comment by stcheng** [comment]
Thanks for the explanation. I'll close this. I don't know if we could use the SAI_PORT_ATTR_HW_LANE_LIST as the default value? This is the attribute that every port would have when creating the port. And also the lane information could be shown in the database and also dumped.

**Comment by kcudnik** [comment]
this null:null does not apply only to port object but to all objects, so your trick won't work
